language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo g


after_script:
  - cd ./public
  - git init
  - git config --global user.name "wangxiurui"
  - git config --global user.email "510717456@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
     - blog     
env:
 global:
   - GH_REF: github.com/wangxiurui/wangxiurui.github.io.git